### PR TITLE
lab02 pull request

### PR DESCRIPTION
**Pull request by colerogers**

### CODE REVIEW

**Comment by colerogers** [comment]
Lab04-

fixes issue #3 
fixes issue #4 
fixes issue #6 
fixes issue #9

**Comment by colerogers** [comment]
Lab07-

commit b4fdaf4: fixes issue #11

**Comment by kevinchanucsb** [comment]
Lab07-
fixed issue 13, and fixed bug in ToggleMusic in settings

**Comment by colerogers** [comment]
lab07-
fixes issue #7 by adding 2 new levels for the player when all the pellets are collected

**Comment by ntpincus** [comment]
Issues for the next generation of students
###Cole Rogers, Kevin Chan

##1) Pause/Unpause button##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/10

##2) Center Gamemap ##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/1

##3) Fix Ghost AI ##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/2

##4) Difficulty button push##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/14

##5) Add test cases ##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/8

##6) Add more Ghosts && Refactor ##
https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/issues/15

**Pull request merged**
